[package]
name = "canvas-lms"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ts-definitions-canvas-lms"
path = "src/ts_definitions.rs"
required-features = ["typescript-definitions"]

[features]
client = ["futures", "futures-timer", "hyper"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
miette = "3.2"
thiserror = "1.0"
tracing = "0.1.29"
futures = { version = "0.3", optional = true }
futures-timer = { version = "3.0", optional = true }

[dependencies.hyper]
version = "0.14"
features = ["client", "http1", "http2", "tcp"]
optional = true

[dependencies.typescript-definitions]
git = "https://github.com/onelson/typescript-definitions.git"
branch = "no-debug-attrs"
optional = true
