services:
  oil_db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: paint
  
  oil_db_ui:
    image: mongo-express
    restart: always
    ports:
      - 4220:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: paint
      ME_CONFIG_MONGODB_URL: mongodb://root:paint@oil_db:27017/
    depends_on:
      - oil_db