services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: paint

  mongo_ui:
    image: mongo-express
    restart: always
    ports:
      - 4201:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:paint@mongo:27017/
    depends_on:
      - mongo
