[package]
name = "pigment"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
async-trait = "0.1"
async-stream = "0.3"
tokio = { version = "1.13", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
canvas-lms = { path = "../canvas" }
log = "0.4"
pretty_env_logger = "0.4"
miette = { version = "3.2", features = ["fancy"] }

[[bin]]
name = "pigment"
path = "src/server/main.rs"
