[package]
name = "pigment"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.13", features = ["rt-multi-thread"] }
tarpc = "0.27"
canvas-lms = { path = "../canvas" }
log = "0.4"
pretty_env_logger = "0.4"

[[bin]]
name = "pigment"
path = "src/server/main.rs"

[[bin]]
name = "pigment-client"
path = "src/client.rs"