[package]
name = "glaze-wasm"
version = "0.1.0"
authors = ["Max Niederman <max@maxniederman.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
futures = "0.3"
heapless = "0.7"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = "0.3"
indexed_db_futures = "0.2"
serde = "1.0"
crossbeam-skiplist = { git = "https://github.com/crossbeam-rs/crossbeam", tag = "crossbeam-0.8.1" }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4", optional = true }

canvas-lms = { path = "../canvas" }
pigment = { path = "../pigment" }
ebauche-rpc = { path = "../ebauche-rpc" }

[dev-dependencies]
wasm-bindgen-test = "0.3"
