[package]
name = "glaze-wasm"
version = "0.1.0"
authors = ["Max Niederman <max@maxniederman.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "tracing-wasm"]

[dependencies]
futures = "0.3"
heapless = "0.7"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = "0.3"
gloo-storage = "0.2"
indexed_db_futures = "0.2"
ws_stream_wasm = "0.7"
chrono = "0.4"
bincode = "1.3"
serde = "1.0"
erased-serde = "0.3"
crossbeam-skiplist = { git = "https://github.com/crossbeam-rs/crossbeam", tag = "crossbeam-0.8.1" }
miette = "3.3"
tracing = "0.1"
console_error_panic_hook = { version = "0.1", optional = true }
tracing-wasm = { version = "0.2", optional = true }
canvas-lms = { path = "../canvas" }
pigment = { path = "../pigment" }
ebauche-rpc = { path = "../ebauche-rpc" }


[dev-dependencies]
wasm-bindgen-test = "0.3"
