[package]
name = "pigment"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.7"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.0"
canvas-lms = { path = "../canvas" }
tracing = "0.1"
miette = { version = "3.2", features = ["fancy"] }
thiserror = "1.0"
