[package]
name = "ebauche-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canvas-lms = { path = "../canvas" }
pigment = { path = "../pigment" }
futures = "0.3"
serde = "1.0"
tracing = "0.1"
miette = { version = "3.2", features = ["fancy"] }
thiserror = "1.0"
