[package]
name = "oil"
version = "0.1.0"
edition = "2021"

[dependencies]
canvas-lms = { path = "../packages/canvas" }
pigment = { path = "../packages/pigment" }
ebauche-rpc = { path = "../packages/ebauche-rpc" }
futures = "0.3"
tokio = { version = "1.0", features = ["rt-multi-thread"] }
poem = { version = "1.2", features = ["websocket"] }
poem-openapi = { version = "1.2", features = ["swagger-ui"] }
serde = "1.0"
bincode = "1.0"
async-bincode = "0.6"
chrono = { version = "0.4", features = ["serde"] }
miette = { version = "3.2", features = ["fancy"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }