[package]
name = "oil"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["rt-multi-thread"] }
poem = "1.2"
poem-openapi = { version = "1.2", features = ["swagger-ui"] }
miette = { version = "3.2", features = ["fancy"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }