[package]
name = "varnish"
version = "0.1.0"
edition = "2021"

[dependencies]
perseus = { version = "0.3.0", features = ["hydrate"] }
sycamore = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
